# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

env:
  #- MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  # for unregistered package, it must be added with `Pkg.pkg"add url"`
  - julia -e 'using Pkg;
    Pkg.pkg"add https://github.com/kura-okubo/SeisIO.jl"; Pkg.build("SeisIO");
    Pkg.pkg"add https://github.com/tclements/Noise.jl"; Pkg.build("SeisIO");
    cd(Pkg.dir("SeisXcorrelation")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia --project=docs/ -e 'using Pkg;
        Pkg.develop(PackageSpec(path=pwd()));
        Pkg.instantiate();
        Pkg.build("SeisXcorrelation")'
  # install mpi environment
  - sh ./conf/travis-install-mpi.sh $MPI_IMPL
  - export PATH=$HOME/OpenMPI/bin:$HOME/MPICH/bin:$PATH
  - export CC=mpicc
  - export FC=mpif90
  - export TMPDIR=/tmp
  - export OMPI_MCA_btl=self,tcp

notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.1
      script:
          - julia --project=docs/ -e 'using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();
            Pkg.build("SeisXcorrelation")'
          - julia -e 'using Pkg;
            cd(Pkg.dir("SeisXcorrelation")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
      after_success: skip
